github: [Prince25]
custom: ['https://www.buymeacoffee.com/PrinceSingh', 'https://www.paypal.com/donate/?business=3Y9NEYR4TURT8&item_name=Making+software+and+hacking+the+world%21+%E2%99%A5&currency_code=USD']
